"""add_org_group_wash

Revision ID: 2a6c986bfa11
Revises: f5cdb0056c48
Create Date: 2024-05-07 13:54:12.761200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6c986bfa11'
down_revision: Union[str, None] = 'f5cdb0056c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('service', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'service')
    # ### end Alembic commands ###
