"""add_org_group_wash

Revision ID: f5cdb0056c48
Revises: fbeacd6ad2a5
Create Date: 2024-05-06 13:28:44.236962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5cdb0056c48'
down_revision: Union[str, None] = 'fbeacd6ad2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), server_default='', nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('display_name', sa.String(), server_default='', nullable=False),
    sa.Column('version', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), server_default='', nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('version', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('washes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), server_default='', nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('version', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'chats', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'washes', ['wash_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_table('washes')
    op.drop_table('groups')
    op.drop_table('organizations')
    # ### end Alembic commands ###
